const days=[['Pon','13'],['Wt','14'],['Śr','15'],['Czw','16'],['Pt','17'],['Sob','18'],['Nd','19']];
const hours=['08:00','09:30','11:00','13:00','15:30','17:00','18:30'];
const names=['Poniedziałek','Wtorek','Środa','Czwartek','Piątek','Sobota','Niedziela'];
let selectedDay=0,selectedHour='';
const bookings=JSON.parse(localStorage.getItem('rino-bookings')||'null')||[
  {day:'15',month:'LIP',title:'Tenis z Markiem Kowalskim',meta:'Środa, 18:30 · Korty Legia, Warszawa'},
  {day:'18',month:'LIP',title:'Padel z Anną Sową',meta:'Sobota, 10:00 · Padel Club Wilanów'}
];
const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
let authMode='register',currentUser=null;
const api=async(path,options={})=>{const token=localStorage.getItem('rino-token');const response=await fetch(path,{...options,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{ }),...(options.headers||{})}});const data=await response.json().catch(()=>({error:'Błąd odpowiedzi serwera'}));if(!response.ok)throw new Error(data.error||'Wystąpił błąd');return data};
function showToast(text){const el=$('#toast');el.textContent=text;el.classList.add('show');clearTimeout(showToast.t);showToast.t=setTimeout(()=>el.classList.remove('show'),2500)}
function showView(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===id));window.scrollTo({top:0,behavior:'smooth'})}
$$('.nav button').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view)));
async function searchTrainers(){const p=new URLSearchParams();[['q','#searchQuery'],['discipline','#discipline'],['district','#district'],['maxPrice','#maxPrice']].forEach(([key,id])=>{if($(id).value)p.set(key,$(id).value)});const box=$('#trainerResults');box.innerHTML='<div class="card empty">Szukam najlepszych trenerów…</div>';try{const data=await api('/api/trainers?'+p);if($('#district').options.length===1)data.filters.districts.forEach(v=>$('#district').add(new Option(v,v)));box.innerHTML=data.items.length?data.items.map(t=>`<article class="trainer"><div class="trainer-avatar">${t.initials}</div><div><h3>${t.name} ${t.verified?'✓':''}</h3><p>${t.discipline[0].toUpperCase()+t.discipline.slice(1)} · ${t.district}</p><p>★ ${t.rating} (${t.reviews}) · ${t.level}</p></div><div class="price">${t.price} zł<small style="display:block;color:var(--muted)">/ godz.</small></div><button class="primary" data-trainer="${t.id}">Zobacz terminy</button></article>`).join(''):'<div class="card empty">Nie znaleźliśmy trenerów dla tych filtrów.</div>';$$('[data-trainer]').forEach(b=>b.onclick=()=>{showView('calendar');showToast('Pokazujemy wolne terminy wybranego trenera')})}catch(e){box.innerHTML=`<div class="card empty">${e.message}. Uruchom stronę poleceniem <strong>npm start</strong>.</div>`}}
$('#searchForm').addEventListener('submit',e=>{e.preventDefault();searchTrainers()});
function renderWeek(){const week=$('#week');week.innerHTML='';days.forEach((d,i)=>{const b=document.createElement('button');b.className='day'+(i===selectedDay?' selected':'');b.innerHTML=`<small>${d[0]}</small><strong>${d[1]}</strong>${i<6?'<span class="dot"></span>':''}`;b.onclick=()=>{selectedDay=i;selectedHour='';renderWeek();renderSlots()};week.appendChild(b)})}
function renderSlots(){const box=$('#slots');$('#slotTitle').textContent=`${names[selectedDay]}, ${days[selectedDay][1]} lipca`;box.innerHTML='';hours.forEach((h,i)=>{const b=document.createElement('button');b.className='slot'+(h===selectedHour?' selected':'');b.textContent=h;b.disabled=(selectedDay+i)%6===4;b.onclick=()=>{selectedHour=h;renderSlots();$('#slotHint').innerHTML=`Wybrano <strong>${h}</strong>. <button class="primary" id="confirm" style="margin-top:12px;width:100%">Potwierdź rezerwację</button>`;$('#confirm').onclick=confirmBooking};box.appendChild(b)})}
function confirmBooking(){if(!selectedHour)return;bookings.unshift({day:days[selectedDay][1],month:'LIP',title:'Tenis z Markiem Kowalskim',meta:`${names[selectedDay]}, ${selectedHour} · Korty Legia, Warszawa`});localStorage.setItem('rino-bookings',JSON.stringify(bookings));renderBookings();showToast('Trening został zarezerwowany');showView('bookings')}
function renderBookings(){const list=$('#bookingList');list.innerHTML=bookings.map(b=>`<article class="booking"><div class="datebox"><strong>${b.day}</strong>${b.month}</div><div><h3>${b.title}</h3><p>${b.meta}</p></div><span class="tag">Potwierdzona</span></article>`).join('')}
$('#goBooking').onclick=()=>{selectedDay=0;renderWeek();renderSlots();showToast('Wybierz dzień i godzinę')};$$('[data-open-calendar]').forEach(b=>b.onclick=()=>showView('calendar'));
$('#chatForm').addEventListener('submit',e=>{e.preventDefault();const input=$('#chatInput'),value=input.value.trim();if(!value)return;const msg=document.createElement('div');msg.className='bubble me';msg.innerHTML=`${value.replace(/[<>]/g,'')}<time>teraz</time>`;$('#messages').appendChild(msg);input.value='';msg.scrollIntoView({behavior:'smooth'});showToast('Wiadomość wysłana')});
$$('.switch').forEach(s=>s.addEventListener('click',()=>{s.classList.toggle('on');s.setAttribute('aria-pressed',s.classList.contains('on'));showToast('Ustawienia przypomnień zapisane')}));
function setAuthMode(mode){authMode=mode;$$('[data-auth]').forEach(b=>b.classList.toggle('active',b.dataset.auth===mode));const register=mode==='register';$('#authTitle').textContent=register?'Załóż konto':'Zaloguj się';$('#nameField').style.display=register?'block':'none';$('#roleField').style.display=register?'block':'none';$('#termsField').style.display=register?'flex':'none';$('#authSubmit').textContent=register?'Załóż konto':'Zaloguj się';$('#authForm').elements.password.autocomplete=register?'new-password':'current-password';$('#authError').textContent=''}
$$('[data-auth]').forEach(b=>b.onclick=()=>setAuthMode(b.dataset.auth));$('#accountButton').onclick=()=>{$('#authDialog').showModal();showAccountState()};$('#closeAuth').onclick=()=>$('#authDialog').close();
const requestedRole=new URLSearchParams(window.location.search).get('role');if(requestedRole==='trainer')$('#authForm').elements.role.value='trainer';
const requestedAuthMode=window.RinoAuthRoute.modeFromHash(window.location.hash);if(requestedAuthMode){setAuthMode(requestedAuthMode);$('#authDialog').showModal();showAccountState()}
function updateUser(user){currentUser=user;const initials=user?user.name.split(/\s+/).map(v=>v[0]).slice(0,2).join('').toUpperCase():'+';$('#accountLabel').textContent=user?`Cześć, ${user.name.split(' ')[0]}`:'Załóż konto';$('#accountAvatar').textContent=initials;showAccountState()}
function showAccountState(){const logged=!!currentUser;$('#authForm').classList.toggle('hidden',logged);$('#authTabs').classList.toggle('hidden',logged);$('#accountBox').classList.toggle('active',logged);if(logged){$('#authTitle').textContent='Twoje konto';$('#modalAvatar').textContent=$('#accountAvatar').textContent;$('#modalName').textContent=currentUser.name;$('#modalEmail').textContent=currentUser.email+' · '+(currentUser.role==='trainer'?'trener':'klient')}}
$('#authForm').addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.currentTarget),payload={email:f.get('email'),password:f.get('password')};if(authMode==='register')Object.assign(payload,{name:f.get('name'),role:f.get('role'),acceptTerms:f.get('acceptTerms')==='on'});$('#authSubmit').disabled=true;$('#authError').textContent='';try{const data=await api(`/api/auth/${authMode}`,{method:'POST',body:JSON.stringify(payload)});localStorage.setItem('rino-token',data.token);updateUser(data.user);showToast(authMode==='register'?'Konto zostało utworzone':'Zalogowano pomyślnie')}catch(err){$('#authError').textContent=err.message}finally{$('#authSubmit').disabled=false}});
$('#logoutButton').onclick=async()=>{try{await api('/api/auth/logout',{method:'POST'})}catch{}localStorage.removeItem('rino-token');updateUser(null);setAuthMode('login');showToast('Wylogowano')};
async function restoreSession(){if(!localStorage.getItem('rino-token'))return;try{const data=await api('/api/auth/me');updateUser(data.user)}catch{localStorage.removeItem('rino-token')}}
renderWeek();renderSlots();renderBookings();searchTrainers();restoreSession();
